/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Classes.Cliente;
import static Formularios.freLogin.cliente;
import Interfaces.ClienteOperacao;

import javax.swing.JOptionPane;


/**
 *
 * @author HWILL
 */
public class cadastrocliente extends javax.swing.JInternalFrame {

    Cliente c = new Cliente();

    private final ClienteOperacao clienteinserir = new ClienteOperacao();

    /**
     * Creates new form TelaCAdClient
     */
    public cadastrocliente() {
        initComponents();
    }

    public void destbtn(){
           this.Alterar.setVisible(false);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcontacto = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        boxnacionalidade = new javax.swing.JComboBox<>();
        boxtipodocumento = new javax.swing.JComboBox<>();
        boxsexo = new javax.swing.JComboBox<>();
        txtnumerdocum = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        boxdistrito = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        salvar_cliente = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        textmorada = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Alterar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("CADASTRO CLIENTE");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jLabel1.setText("Nacionalidade:");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jLabel2.setText("Nome Completo:");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jLabel4.setText("Sexo:");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jLabel6.setText("Contacto:");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jLabel7.setText("Nº de Documento:");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jLabel8.setText("Tipo de Documento:");

        txtcontacto.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        txtcontacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcontactoKeyReleased(evt);
            }
        });

        txtnome.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });

        boxnacionalidade.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        boxnacionalidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma opção", "Santomense", "Angolano", "Cabo Verdiano", "Guinieense", "Portugês", "Brasileiro", "Holandes", "Moçambicano", "Gabonês", "Nigériano", "Françês", "Alemâo", "Turko" }));
        boxnacionalidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxnacionalidadeMouseClicked(evt);
            }
        });

        boxtipodocumento.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        boxtipodocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma opção", "Bilhete de Identidade", "Passaporte" }));

        boxsexo.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        boxsexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma opção", "Masculino", "Feminino" }));

        txtnumerdocum.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        txtnumerdocum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnumerdocumKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jLabel9.setText("Distrito:");

        boxdistrito.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        boxdistrito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma opção", "Água Grande", "Lobata", "Mé-zochi", "Cantagalo", "Cauê", "Paguê" }));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/clientes.png"))); // NOI18N

        salvar_cliente.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        salvar_cliente.setForeground(new java.awt.Color(0, 51, 255));
        salvar_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/btnsave.png"))); // NOI18N
        salvar_cliente.setText("Salvar");
        salvar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_clienteActionPerformed(evt);
            }
        });

        Cancelar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Cancelar.setForeground(new java.awt.Color(255, 0, 51));
        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/btncancel1.png"))); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        textmorada.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jLabel11.setText("Morada:");

        Alterar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Alterar.png"))); // NOI18N
        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(Cancelar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(boxtipodocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boxsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(boxdistrito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(boxnacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(9, 9, 9))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txtnumerdocum, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Alterar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textmorada, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(salvar_cliente)
                                .addGap(20, 20, 20))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtcontacto, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 1, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel2)
                    .addContainerGap(531, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boxnacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxtipodocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnumerdocum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcontacto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boxdistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textmorada, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvar_cliente)
                    .addComponent(Alterar)
                    .addComponent(Cancelar))
                .addGap(53, 53, 53))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(334, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void salvar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_clienteActionPerformed
        if (this.txtnome.getText().length() <= 0 ||   this.textmorada.getText().length() <= 0 || this.txtnumerdocum.getText().length() <= 0|| this.txtcontacto.getText().length() <= 0 
                ||this.boxnacionalidade.getSelectedItem().equals("Selecione uma opção")||this.boxsexo.getSelectedItem().equals("Selecione uma opção")||this.boxdistrito.getSelectedItem().equals("Selecione uma opção")||this.boxtipodocumento.getSelectedItem().equals("Selecione uma opção")) {
            JOptionPane.showMessageDialog(this, "Preenche todos os campos");
        } else if (this.txtcontacto.getText().length() <7 || this.txtcontacto.getText().length() > 7) {

            JOptionPane.showMessageDialog(this, "Contactos Invaido");

        }  else if (this.txtnumerdocum.getText().length() <6 || this.txtnumerdocum.getText().length() > 7) {

            JOptionPane.showMessageDialog(this, "Numero de Documento Invaido");

        }else {

            c.setNome(this.txtnome.getText());
            c.setSexo(this.boxsexo.getSelectedItem() + "");
            c.setTipo_documento(this.boxtipodocumento.getSelectedItem() + "");
            c.setNumero_documento(this.txtnumerdocum.getText());
            c.setNacionalidade(this.boxnacionalidade.getSelectedItem()+"");
            c.setMorada(this.textmorada.getText());
            c.setContacto(Integer.parseInt(this.txtcontacto.getText()));
            c.setDistrito(this.boxdistrito.getSelectedItem() + "");
            clienteinserir.Cadastra(c);
           
            limpar();
           

    }//GEN-LAST:event_salvar_clienteActionPerformed
      
    }
     public void Pintar() {
        // ID, nome, sexo, data_nascimento, email, cargo, carteira_motorista, contacto 
        this.txtnome.setText(cliente.getNome());
        this.boxsexo.setSelectedItem(cliente.getSexo());
        this.boxdistrito.setSelectedItem(cliente.getDistrito());
        this.textmorada.setText(cliente.getMorada());
        this.boxnacionalidade.setSelectedItem(cliente.getNacionalidade());
        this.boxtipodocumento.setSelectedItem(cliente.getTipo_documento());
        this.txtnumerdocum.setText(cliente.getNumero_documento());
        this.txtcontacto.setText(cliente.getContacto()+"");
        
        
        
        this.salvar_cliente.setVisible(false);
            
        }
        
    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:this.
        dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void txtnumerdocumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumerdocumKeyReleased
        // TODO add your handling code here:souse
       
        if(boxtipodocumento.getSelectedItem()=="Bilhete de Identidade"){ 
        int valor;
        try{
            valor = Integer.parseInt(txtnumerdocum.getText());
        }catch(Exception e){
           
          txtnumerdocum.setText("");
         
        }
       }  
    }//GEN-LAST:event_txtnumerdocumKeyReleased

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
//       this.salvar_cliente
 if (this.txtnome.getText().length() <= 0 ||   this.textmorada.getText().length() <= 0 || this.txtnumerdocum.getText().length() <= 0|| this.txtcontacto.getText().length() <= 0 
                ||this.boxnacionalidade.getSelectedItem().equals("Selecione uma opção")||this.boxsexo.getSelectedItem().equals("Selecione uma opção")||this.boxdistrito.getSelectedItem().equals("Selecione uma opção")||this.boxtipodocumento.getSelectedItem().equals("Selecione uma opção")) {
            JOptionPane.showMessageDialog(this, "Preenche todos os campos");
        } else if (this.txtcontacto.getText().length() <7 || this.txtcontacto.getText().length() > 7) {

            JOptionPane.showMessageDialog(this, "Contactos Invaido");

        }  else if (this.txtnumerdocum.getText().length() <6 || this.txtnumerdocum.getText().length() > 7) {

            JOptionPane.showMessageDialog(this, "Numero de Documento Invaido");

        }else {

            cliente.setNome(this.txtnome.getText());
            cliente.setSexo(this.boxsexo.getSelectedItem() + "");
            cliente.setTipo_documento(this.boxtipodocumento.getSelectedItem() + "");
            cliente.setNumero_documento(this.txtnumerdocum.getText());
            cliente.setMorada(this.textmorada.getText());
            cliente.setNacionalidade(this.boxnacionalidade.getSelectedItem()+"");
            cliente.setContacto(Integer.parseInt(this.txtcontacto.getText()));
            cliente.setDistrito(this.boxdistrito.getSelectedItem() + "");
            clienteinserir.Alterar(cliente);
           
            limpar();
    }//GEN-LAST:event_AlterarActionPerformed
 }
    private void txtcontactoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontactoKeyReleased
       int valo=0;
       try{
            valo = Integer.parseInt(txtcontacto.getText());
        }catch(Exception e){
           
          txtcontacto.setText("");
         
        }
    }//GEN-LAST:event_txtcontactoKeyReleased

    private void boxnacionalidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxnacionalidadeMouseClicked
     
    }//GEN-LAST:event_boxnacionalidadeMouseClicked
public void limpar() {
        // TODO add your handling code here:
        this.txtnome.setText("");
        this.boxsexo.setSelectedIndex(0);
        this.boxnacionalidade.setSelectedIndex(0);
        this.txtnumerdocum.setText("");
        this.textmorada.setText("");
        this.txtcontacto.setText("");
        this.boxdistrito.setSelectedIndex(0);
         this.boxtipodocumento.setSelectedIndex(0);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Alterar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JComboBox<String> boxdistrito;
    private javax.swing.JComboBox<String> boxnacionalidade;
    private javax.swing.JComboBox<String> boxsexo;
    private javax.swing.JComboBox<String> boxtipodocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton salvar_cliente;
    private javax.swing.JTextField textmorada;
    private javax.swing.JTextField txtcontacto;
    public javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtnumerdocum;
    // End of variables declaration//GEN-END:variables

  
}
