/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import static Formularios.freLogin.func;
import Interfaces.FuncionarioOperacao;
import javax.swing.JOptionPane;

/**
 *
 * @author HWILL
 */
public class Cadastrafunc extends javax.swing.JInternalFrame {

    private final FuncionarioOperacao funcinserir = new FuncionarioOperacao();
   

    /**
     * Creates new form TelaCAdClient
     */
    public Cadastrafunc() {
        initComponents();
        
    }

    public void limpar() {
        this.txtnome.setText("");
        this.boxsexo.setSelectedIndex(0);
        this.txtnascimento.setText("");
        this.boxcargo.setSelectedIndex(0);
        this.boxdistrito.setSelectedIndex(0);
        this.txtmorada.setText("");
        this.boxtipodocumento.setSelectedIndex(0);
        this.txtnumerdocum.setText("");
        this.boxnacionalidade.setSelectedIndex(0);
        this.txtcontacto.setText("");
    }

    public void Pintar() {
        this.txtnome.setText(func.getNome());
        this.boxsexo.setSelectedItem(func.getSexo());
        this.txtnascimento.setText(func.getData_nascimento());
        this.boxcargo.setSelectedItem(func.getCargo());
        func.getId_funcionario();
        this.boxdistrito.setSelectedItem(func.getDistrito());
        this.txtmorada.setText(func.getMorada());
        this.boxtipodocumento.setSelectedItem(func.getTipo_documento());
        this.txtnumerdocum.setText(func.getNumero_documento());
        this.boxnacionalidade.setSelectedItem(func.getNacionalidade());
        this.txtcontacto.setText(func.getContacto() + "");
       this.salvar_func.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcontacto = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        boxnacionalidade = new javax.swing.JComboBox<>();
        boxtipodocumento = new javax.swing.JComboBox<>();
        boxsexo = new javax.swing.JComboBox<>();
        txtnascimento = new javax.swing.JTextField();
        txtnumerdocum = new javax.swing.JTextField();
        boxdistrito = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        salvar_func = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        boxcargo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtmorada = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("CADASTRO FUNCIONARIO");
        setVisible(true);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jLabel1.setText("Nacionalidade:");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jLabel2.setText("Nome Completo:");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jLabel3.setText("Data nascimento:");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jLabel4.setText("Sexo:");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jLabel6.setText("Contacto:");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jLabel7.setText("Nº de Documento:");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jLabel8.setText("Tipo de Documento:");

        txtcontacto.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        txtcontacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcontactoKeyReleased(evt);
            }
        });

        txtnome.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        txtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnomeKeyReleased(evt);
            }
        });

        boxnacionalidade.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        boxnacionalidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma opção", "Santomense", "Angolano", "Cabo Verdiano", "Guinieense", "Portugês", "Brasileiro", "Holandes", "Moçambicano", "Gabonês", "Nigériano", "Françês", "Alemâo", "Turko" }));

        boxtipodocumento.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        boxtipodocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma opção", "Bilhete de Identidade", "Passaporte" }));

        boxsexo.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        boxsexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma opção", "Masculino", "Feminino" }));

        txtnascimento.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N

        txtnumerdocum.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        txtnumerdocum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnumerdocumKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnumerdocumKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumerdocumKeyTyped(evt);
            }
        });

        boxdistrito.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        boxdistrito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma opção", "Água Grande", "Lobata", "Mé-zochi", "Cantagalo", "Cauê", "Paguê" }));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Funcio.png"))); // NOI18N

        salvar_func.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        salvar_func.setForeground(new java.awt.Color(0, 51, 255));
        salvar_func.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/btnsave.png"))); // NOI18N
        salvar_func.setText("Salvar");
        salvar_func.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        salvar_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_funcActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/btncancel1.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(0, 204, 0));
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jLabel11.setText("Cargo:");

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jLabel12.setText("Distrito:");

        boxcargo.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        boxcargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma opção", "Recepcionista", "Motorista", "Secretária", "Fachineira", "Mecanico de Manutenção" }));
        boxcargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxcargoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jLabel13.setText("Morada:");

        txtmorada.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        txtmorada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmoradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButton2)
                        .addGap(142, 142, 142)
                        .addComponent(btnAlterar)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(246, 246, 246))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxtipodocumento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1))
                                        .addGap(10, 10, 10)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(boxsexo, javax.swing.GroupLayout.Alignment.LEADING, 0, 198, Short.MAX_VALUE)
                                    .addComponent(boxnacionalidade, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtnome, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnascimento)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnumerdocum)
                                    .addComponent(boxcargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(42, 42, 42)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtmorada))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boxdistrito, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcontacto, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(salvar_func)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxnacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxtipodocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcontacto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumerdocum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxdistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtmorada, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salvar_func, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxcargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxcargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxcargoActionPerformed

    private void salvar_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_funcActionPerformed

        // TODO add your handling code here:
        if (this.txtnome.getText().length() <= 0 || this.txtnascimento.getText().length() <= 0 || this.txtcontacto.getText().length() <= 0 || this.txtmorada.getText().length() <= 0 || this.txtnumerdocum.getText().length() <= 0
                || this.boxcargo.getSelectedItem().equals("Selecione uma opção")|| this.boxsexo.getSelectedItem().equals("Selecione uma opção")|| this.boxtipodocumento.getSelectedItem().equals("Selecione uma opção")|| this.boxnacionalidade.getSelectedItem().equals("Selecione uma opção")
                || this.boxdistrito.getSelectedItem().equals("Selecione uma opção")) {
            JOptionPane.showMessageDialog(this, "Preenxe todos os campos");
        } else if (this.txtcontacto.getText().length() < 7 || this.txtcontacto.getText().length() > 7) {

            JOptionPane.showMessageDialog(this, "Contactos Invaido");

        } else if (this.txtnumerdocum.getText().length() < 6 || this.txtnumerdocum.getText().length() > 7) {
            JOptionPane.showMessageDialog(this, "Numero documento Invalido");
        } else {

            func.setNome(this.txtnome.getText());
            func.setSexo(this.boxsexo.getSelectedItem() + "");
            func.setData_nascimento(this.txtnascimento.getText());
            func.setCargo(this.boxcargo.getSelectedItem() + "");
            func.setContacto(Integer.parseInt(this.txtcontacto.getText()));
            func.setDistrito(this.boxdistrito.getSelectedItem() + "");
            func.setMorada(this.txtmorada.getText());
            func.setTipo_documento(this.boxtipodocumento.getSelectedItem() + "");
            func.setNumero_documento(this.txtnumerdocum.getText());
            func.setNacionalidade(this.boxnacionalidade.getSelectedItem() + "");
            funcinserir.Cadastra(func);

            limpar();
        }
    }//GEN-LAST:event_salvar_funcActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (this.txtnome.getText().length() <= 0 || this.txtnascimento.getText().length() <= 0 || this.txtcontacto.getText().length() <= 0 || this.txtmorada.getText().length() <= 0 || this.txtnumerdocum.getText().length() <= 0
                || this.boxcargo.getSelectedItem().equals("Selecione uma opção")|| this.boxsexo.getSelectedItem().equals("Selecione uma opção")|| this.boxtipodocumento.getSelectedItem().equals("Selecione uma opção")|| this.boxnacionalidade.getSelectedItem().equals("Selecione uma opção")
                || this.boxdistrito.getSelectedItem().equals("Selecione uma opção")) {
            JOptionPane.showMessageDialog(this, "Preenxe todos os campos");
        } else if (this.txtcontacto.getText().length() < 7 || this.txtcontacto.getText().length() > 7) {

            JOptionPane.showMessageDialog(this, "Contactos Invaido");

        } else if (this.txtnumerdocum.getText().length() < 6 || this.txtnumerdocum.getText().length() > 7) {
            JOptionPane.showMessageDialog(this, "Numero documento Invalido");
        } else {
            func.setNome(this.txtnome.getText());
            func.setSexo(this.boxsexo.getSelectedItem() + "");
            func.setData_nascimento(this.txtnascimento.getText());
            func.setCargo(this.boxcargo.getSelectedItem() + "");
            func.setContacto(Integer.parseInt(this.txtcontacto.getText()));
            func.setDistrito(this.boxdistrito.getSelectedItem() + "");
            func.setMorada(this.txtmorada.getText());
            func.setTipo_documento(this.boxtipodocumento.getSelectedItem() + "");
            
            func.setNumero_documento(this.txtnumerdocum.getText());
            func.setNacionalidade(this.boxnacionalidade.getSelectedItem() + "");
            funcinserir.Alterar(func);

            limpar();
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtnumerdocumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumerdocumKeyReleased
        // TODO add your handling code here:
        if (boxtipodocumento.getSelectedItem() == "Bilhete de Identidade") {
            int valor = 0;
            try {
                valor = Integer.parseInt(txtnumerdocum.getText());
            } catch (NumberFormatException ex) {

                txtnumerdocum.setText("");
            }

        }
    }//GEN-LAST:event_txtnumerdocumKeyReleased

    private void txtnumerdocumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumerdocumKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtnumerdocumKeyPressed

    private void txtnumerdocumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumerdocumKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtnumerdocumKeyTyped

    private void txtnomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomeKeyReleased

    }//GEN-LAST:event_txtnomeKeyReleased

    private void txtmoradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmoradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmoradaActionPerformed

    private void txtcontactoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontactoKeyReleased
        // TODO add your handling code here:
        int valo = 0;
        try {
            valo = Integer.parseInt(txtcontacto.getText());
        } catch (Exception e) {

            txtcontacto.setText("");

        }
    }//GEN-LAST:event_txtcontactoKeyReleased
    public void desativar(){
        this.btnAlterar.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxcargo;
    private javax.swing.JComboBox<String> boxdistrito;
    private javax.swing.JComboBox<String> boxnacionalidade;
    private javax.swing.JComboBox<String> boxsexo;
    private javax.swing.JComboBox<String> boxtipodocumento;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton salvar_func;
    private javax.swing.JTextField txtcontacto;
    private javax.swing.JTextField txtmorada;
    private javax.swing.JTextField txtnascimento;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtnumerdocum;
    // End of variables declaration//GEN-END:variables
}
