/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Classes.conexao;
import static Formularios.freLogin.aluguer;
import static Formularios.freLogin.veiculo;
import Interfaces.AluguerOpercao;
import Interfaces.AutomovelOperacao;
import funcao.dao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.time.LocalDate;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author HWILL
 */
public class Devolucao extends javax.swing.JInternalFrame {

    LocalDate dare = LocalDate.now();
    ;
    int controladora = 1;
    AluguerOpercao ver = new AluguerOpercao();

    /**
     * Creates new form Devolucao
     */
    public Devolucao() {
        initComponents();
        this.btnVerificar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        table_aluguer = new javax.swing.JTable();
        btnlistar = new javax.swing.JButton();
        btnVerificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcontacto = new javax.swing.JLabel();
        txtnome = new javax.swing.JLabel();
        txtdia = new javax.swing.JLabel();
        txtentrega = new javax.swing.JLabel();
        txtmatricula = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtvalorveiculo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtmarca = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textpesq_locas = new javax.swing.JTextField();
        txtmulta = new javax.swing.JLabel();
        txthora = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setVisible(true);

        table_aluguer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_aluguer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_aluguerMouseClicked(evt);
            }
        });
        table_aluguer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                table_aluguerKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(table_aluguer);

        btnlistar.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        btnlistar.setText("Listar todas ");
        btnlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistarActionPerformed(evt);
            }
        });

        btnVerificar.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        btnVerificar.setText("Devolver Veiculo");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel1.setText("Nome Cliente:");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setText("Contacto:");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setText("Marca do veiculo:");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setText("Data de Entrega:");

        txtcontacto.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtcontacto.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        txtnome.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtnome.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtdia.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtdia.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtentrega.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtentrega.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtmatricula.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtmatricula.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setText("Dias de Atraso:");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel6.setText("Valor do Veiculo:");

        txtvalorveiculo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtvalorveiculo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel7.setText("Valor de Atraso:");

        txtmarca.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtmarca.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel8.setText("Matricula:");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jLabel9.setText("Pesquisar veiculos Alugados:");

        textpesq_locas.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        textpesq_locas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textpesq_locasActionPerformed(evt);
            }
        });
        textpesq_locas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textpesq_locasKeyReleased(evt);
            }
        });

        txtmulta.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtmulta.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txthora.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txthora.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel10.setText("Hora de Entrega:");

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel11.setText("Pagar Valor de Atraso:");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Search.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textpesq_locas, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnlistar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcontacto, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmulta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtvalorveiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtentrega, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(134, 134, 134)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txthora, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVerificar)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textpesq_locas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlistar)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtcontacto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(txtentrega, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(txtvalorveiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtmulta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(txthora, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnVerificar)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    private void btnlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistarActionPerformed
     listar();
    }//GEN-LAST:event_btnlistarActionPerformed
    public void listar() {
        String sql = "SELECT aluger.id_aluger,data_inicio,data_termino, hora_termino, automovel.marca,automovel.matricula,cliente.nome,cliente.contacto,veiculo,valor_aluguer\n"
                + " FROM aluger,cliente,automovel where aluger.id_cliente=cliente.id_cliente and aluger.id_automovel= automovel.id_automovel\n"
                + "And automovel.estado = '0' And veiculo = 'Alugado' ORDER BY aluger.id_aluger ASC";
        dao x = new dao();

        x.Lista_SqlTabela(sql, table_aluguer);
    }


    private void table_aluguerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_aluguerKeyReleased
                  
    }//GEN-LAST:event_table_aluguerKeyReleased

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
        int seleceonado = this.table_aluguer.getSelectedRow();
        int id_aluger = Integer.parseInt(this.table_aluguer.getValueAt(seleceonado, 0) + "");
        LocalDate data = LocalDate.parse(txtentrega.getText());
        //dare = (data);
        boolean seguir=ver.Verificar(data, txthora.getText(), veiculo.getEstado(), txtmatricula.getText(), id_aluger);
        if (seguir==true) {
            
             double r = ver.somar(aluguer.getValor(), Double.parseDouble(txtmulta.getText()));
            ver.devolver(id_aluger, r, dare);
            AutomovelOperacao uur= new AutomovelOperacao() ;
               uur.Alterar( veiculo.getId_Automovel(),veiculo.getEstado());
            this.btnVerificar.setEnabled(false);
     listar();
        }
        
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void table_aluguerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_aluguerMouseClicked
        // TODO add your handling code here:
        if (controladora == 1) {
            int seleceonado = this.table_aluguer.getSelectedRow();
            this.btnVerificar.setEnabled(true);
            LocalDate data = LocalDate.parse(this.table_aluguer.getValueAt(seleceonado, 2).toString());
            String hora = this.table_aluguer.getValueAt(seleceonado, 3).toString();
            String nome = this.table_aluguer.getValueAt(seleceonado, 6).toString();
            String matricula = this.table_aluguer.getValueAt(seleceonado, 5).toString();
            String contacto = this.table_aluguer.getValueAt(seleceonado, 7).toString();
            double valor = Double.parseDouble(this.table_aluguer.getValueAt(seleceonado,9 ).toString());
            aluguer.setValor(valor);
            this.txtnome.setText(nome);
            this.txtcontacto.setText(contacto);
            this.txthora.setText(hora);
            this.txtentrega.setText(data.toString());
            listar(matricula, txtmarca, txtmatricula, txtvalorveiculo);
             txtdia.setText(ver.CalcularPreco(dare, data) + "");
            txtmulta.setText(ver.CalcularPreco(Integer.parseInt(txtdia.getText()), Double.parseDouble(txtvalorveiculo.getText())) + "");
           
        }
    }//GEN-LAST:event_table_aluguerMouseClicked

    private void textpesq_locasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textpesq_locasKeyReleased
        // TODO add your handling code here:
         String sql = "SELECT aluger.id_aluger,data_inicio,data_termino, hora_termino, automovel.marca,automovel.matricula,cliente.nome,cliente.contacto,veiculo,valor_aluguer \n"
                + " FROM aluger,cliente,automovel where aluger.id_cliente=cliente.id_cliente and aluger.id_automovel= automovel.id_automovel\n"
                + "And automovel.estado = '0' And veiculo = 'Alugado'AND automovel.marca LIKE '%"+textpesq_locas.getText()+"%' ORDER BY aluger.id_aluger ASC";
        dao x = new dao();

        x.Lista_SqlTabela(sql, table_aluguer);
        
        
    }//GEN-LAST:event_textpesq_locasKeyReleased

    private void textpesq_locasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textpesq_locasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textpesq_locasActionPerformed
    public void listar(String matriculacarro, JLabel marca, JLabel matricula, JLabel preco) {
        conexao con = new conexao();
        Connection co = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        co = con.getConnection();
        String sql = "SELECT *  FROM `automovel` WHERE `matricula` LIKE '" + matriculacarro + "'";
        try {
            ps = co.prepareStatement(sql);
            rs = ps.executeQuery();
            System.out.println("Ok executandos" + sql);
            rs = ps.executeQuery();

            if (rs.next()) {
                marca.setText(rs.getString("marca"));
                matricula.setText(rs.getString("matricula"));
                preco.setText(rs.getDouble("preco") + "");
                veiculo.setEstado(Boolean.parseBoolean(rs.getString("estado")));
                veiculo.setId_Automovel(rs.getInt("id_automovel"));
            } else {
                JOptionPane.showMessageDialog(null, "Erro");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnVerificar;
    public javax.swing.JButton btnlistar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable table_aluguer;
    private javax.swing.JTextField textpesq_locas;
    private javax.swing.JLabel txtcontacto;
    private javax.swing.JLabel txtdia;
    private javax.swing.JLabel txtentrega;
    private javax.swing.JLabel txthora;
    private javax.swing.JLabel txtmarca;
    private javax.swing.JLabel txtmatricula;
    private javax.swing.JLabel txtmulta;
    private javax.swing.JLabel txtnome;
    private javax.swing.JLabel txtvalorveiculo;
    // End of variables declaration//GEN-END:variables

}
