/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Classes.conexao;
import static Formularios.freLogin.func;
import static Formularios.freLogin.user;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author HWILL
 */
public class JFMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFMenu
     */
    public JFMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        txtdata = new javax.swing.JLabel();
        txthora = new javax.swing.JLabel();
        NomeUsuarioLogado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        javax.swing.JMenuItem cadastro_func_menu = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        cadastra_automo_menu = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        cadastro_cliente_menu = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("                      ");
        setFocusable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1114, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        txtdata.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtdata.setForeground(java.awt.Color.blue);
        txtdata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtdata.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txthora.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txthora.setForeground(java.awt.Color.blue);
        txthora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txthora.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        NomeUsuarioLogado.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        NomeUsuarioLogado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        jLabel1.setText("Usuario:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomeUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txthora, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthora, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NomeUsuarioLogado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(221, 40));

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/house.png"))); // NOI18N
        jMenu2.setText("Home");
        jMenu2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/receptionist.png"))); // NOI18N
        jMenu10.setText("Funcionario");
        jMenu10.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        cadastro_func_menu.setText("Cadastra Funcionario ");
        cadastro_func_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastro_func_menuActionPerformed(evt);
            }
        });
        jMenu10.add(cadastro_func_menu);

        jMenu2.add(jMenu10);

        jMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/ExecutiveCar_Black_icon-icons.com_54904.png"))); // NOI18N
        jMenu13.setText("Automovel");
        jMenu13.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        cadastra_automo_menu.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        cadastra_automo_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/car_add.png"))); // NOI18N
        cadastra_automo_menu.setText("Cadastra Automovel");
        cadastra_automo_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastra_automo_menuActionPerformed(evt);
            }
        });
        jMenu13.add(cadastra_automo_menu);
        jMenu13.add(jSeparator4);

        jMenu2.add(jMenu13);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/userpassword_deusuari_787_1.png"))); // NOI18N
        jMenu6.setText("Usuario");
        jMenu6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jMenuItem6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jMenuItem6.setText("Cadastra Usuario");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jMenuItem7.setText("Alterar Usuario");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenu2.add(jMenu6);
        jMenu2.add(jSeparator3);

        jMenuItem5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jMenuItem5.setText("Mudar de Usuario");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Exit.png"))); // NOI18N
        jMenuItem8.setText("Sair ");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);
        jMenuBar1.add(jMenu3);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Add.png"))); // NOI18N
        jMenu5.setText("Cadastro");
        jMenu5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/user_person_people_6100_2.png"))); // NOI18N
        jMenu9.setText("Cliente");
        jMenu9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        cadastro_cliente_menu.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        cadastro_cliente_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/menuadcliente.png"))); // NOI18N
        cadastro_cliente_menu.setText("Cadastra Cliente");
        cadastro_cliente_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastro_cliente_menuActionPerformed(evt);
            }
        });
        jMenu9.add(cadastro_cliente_menu);

        jMenu5.add(jMenu9);

        jMenuBar1.add(jMenu5);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/cart.png"))); // NOI18N
        jMenu1.setText("Serviços");
        jMenu1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jMenuItem2.setText("Venda");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jMenuItem3.setText("Aluguer");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jMenuItem1.setText("Devolução do Viculos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/folder_user.png"))); // NOI18N
        jMenu4.setText("Arquivos");
        jMenu4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/folder_explore.png"))); // NOI18N
        jMenuItem4.setText("Pesquisar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastro_cliente_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastro_cliente_menuActionPerformed
        // TODO add your handling code here:
        cadastrocliente cadastrar = new cadastrocliente();
        jDesktopPane1.add(cadastrar);
        cadastrar.destbtn();
        cadastrar.show();

    }//GEN-LAST:event_cadastro_cliente_menuActionPerformed

    private void cadastro_func_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastro_func_menuActionPerformed
//        // TODO add your handling code here:
        Cadastrafunc cadastrar = new Cadastrafunc();
        jDesktopPane1.add(cadastrar);
        cadastrar.desativar();
        cadastrar.show();

    }//GEN-LAST:event_cadastro_func_menuActionPerformed

    private void cadastra_automo_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastra_automo_menuActionPerformed
        cadastraautomovel cadastrar = new cadastraautomovel();
        jDesktopPane1.add(cadastrar);
        cadastrar.btndesativar();
        cadastrar.show();
    }//GEN-LAST:event_cadastra_automo_menuActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        TelaPesquisa pesquisa = new TelaPesquisa();
        jDesktopPane1.add(pesquisa);
        pesquisa.show();

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        TelaVenda venda = new TelaVenda();
        jDesktopPane1.add(venda);
        venda.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        TelaAluguer aluguar = new TelaAluguer();
        jDesktopPane1.add(aluguar);
        aluguar.listarcliente.setVisible(false);
        aluguar.listarcarros.setVisible(false);
        aluguar.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Date sistema = new Date();
        SimpleDateFormat formatar = new SimpleDateFormat("dd/MM/YYYY");
        txtdata.setText(formatar.format(sistema));

        Timer timer = new Timer(1000, new hora());

        timer.start();
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        freLogin trocar = new freLogin();
        this.setVisible(false);
        trocar.setVisible(true);


    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
//        // TODO add your handling code here:
        Devolucao devolver = new Devolucao();
        jDesktopPane1.add(devolver);
        devolver.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        TelaUsuario usuario = new TelaUsuario();
        jDesktopPane1.add(usuario);
        usuario.btnalterar.setVisible(false);
        usuario.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
//        // TODO add your handling code here:
        TelaUsuario usuario = new TelaUsuario();
        jDesktopPane1.add(usuario);
        usuario.btnSalvar.setVisible(false);
        usuario.preencher();
        usuario.show();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    class hora implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent ae) {
            Calendar fh = Calendar.getInstance();
            txthora.setText(String.format("%1$tH:%1$tM:%1$tS", fh));
        }
    }

    public void Mostra(int d) {
        conexao con = new conexao();
        Connection co = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        co = con.getConnection();
        try {
            String sql = "SELECT funcionario.nome,usuario.nome, usuario.senha,usuario.id_usuario\n"
                    + "FROM  usuario\n"
                    + "INNER JOIN funcionario\n"
                    + "On usuario.id_funcionario=funcionario.id_funcionario AND id_usuario = "+d+"";
            ps = co.prepareStatement(sql);
            rs = ps.executeQuery();
            rs.first();
            System.out.println(sql);
            NomeUsuarioLogado.setText(rs.getString("funcionario.nome"));
           user.setNome(rs.getString("usuario.nome"));
            user.setSenha(rs.getString("usuario.senha"));
            user.setId_user(rs.getInt("usuario.id_usuario"));
            System.out.println(user.getId_user());

        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }
//select round(avg(valor_aluguer), 2) from aluger
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel NomeUsuarioLogado;
    private javax.swing.JMenuItem cadastra_automo_menu;
    private javax.swing.JMenuItem cadastro_cliente_menu;
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu9;
    public javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JLabel txtdata;
    private javax.swing.JLabel txthora;
    // End of variables declaration//GEN-END:variables
}
