/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Classes.Automovel;
import Classes.Cliente;
import Classes.Funcionario;
import static Formularios.freLogin.cliente;
import static Formularios.freLogin.func;
import static Formularios.freLogin.veiculo;
import Interfaces.AluguerOpercao;
import Interfaces.AutomovelOperacao;
import Interfaces.ClienteOperacao;
import Interfaces.FuncionarioOperacao;
import funcao.dao;
import java.time.LocalDate;
import java.util.Date; 
import javax.swing.JOptionPane;

/**
 *
 * @author HWILL
 */
public class TelaPesquisa extends javax.swing.JInternalFrame {

    Funcionario f = new Funcionario();
    private final FuncionarioOperacao funcinserir = new FuncionarioOperacao();
    Cliente c = new Cliente();
    private final ClienteOperacao clienteinserir = new ClienteOperacao();
    Automovel au = new Automovel();
    private final ClienteOperacao automovelinserir = new ClienteOperacao();

    /**
     * Creates new form TelaPesquisa
     */
    public TelaPesquisa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabauto = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        table_automovel = new javax.swing.JTable();
        alterar_automovel = new javax.swing.JButton();
        listar_automoveis = new javax.swing.JButton();
        btnexcluir_veiculo = new javax.swing.JButton();
        txtmarca = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_cliente = new javax.swing.JTable();
        btlistar_cliente = new javax.swing.JButton();
        pesquisar_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Excluir_cliente = new javax.swing.JButton();
        btn_altera_clie = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_aluguer = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        listagemdevolucao = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textpesq_loca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        funcionario_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        pesquisa_nome = new javax.swing.JTextField();
        javax.swing.JButton btlistar_func = new javax.swing.JButton();
        btnexc_fun = new javax.swing.JButton();
        btn_func_alterar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_venda = new javax.swing.JTable();
        txtpesq_venda = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setOpaque(true);

        tabauto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        table_automovel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane5.setViewportView(table_automovel);

        alterar_automovel.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        alterar_automovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Alterar.png"))); // NOI18N
        alterar_automovel.setText("Alterar");
        alterar_automovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterar_automovelActionPerformed(evt);
            }
        });

        listar_automoveis.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        listar_automoveis.setText("Listar Todos os Automoveis");
        listar_automoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listar_automoveisActionPerformed(evt);
            }
        });

        btnexcluir_veiculo.setText("Excluir");
        btnexcluir_veiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluir_veiculoActionPerformed(evt);
            }
        });

        txtmarca.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtmarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmarcaKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel9.setText("Pesquisar Marca:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnexcluir_veiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listar_automoveis)
                    .addComponent(alterar_automovel))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listar_automoveis, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(alterar_automovel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addComponent(btnexcluir_veiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabauto.addTab("Automovel", null, jPanel1, "Pesquisar Automoveis");

        table_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane4.setViewportView(table_cliente);

        btlistar_cliente.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btlistar_cliente.setText("Listar todos os clientes");
        btlistar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlistar_clienteActionPerformed(evt);
            }
        });

        pesquisar_nome.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        pesquisar_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisar_nomeActionPerformed(evt);
            }
        });
        pesquisar_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pesquisar_nomeKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("Nome:");

        Excluir_cliente.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Excluir_cliente.setText("Excluir ");
        Excluir_cliente.setEnabled(false);
        Excluir_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Excluir_clienteActionPerformed(evt);
            }
        });

        btn_altera_clie.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btn_altera_clie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Alterar.png"))); // NOI18N
        btn_altera_clie.setText("Editar");
        btn_altera_clie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_altera_clieActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Search.png"))); // NOI18N
        jLabel8.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesquisar_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Excluir_cliente)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btlistar_cliente))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btn_altera_clie)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pesquisar_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btlistar_cliente)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Excluir_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_altera_clie, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabauto.addTab("Cliente", jPanel2);

        table_aluguer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane3.setViewportView(table_aluguer);

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setText("Listar todas as locações");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        listagemdevolucao.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        listagemdevolucao.setText("Listar Devolução");
        listagemdevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listagemdevolucaoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Pesquisar Veiculos Alugados:");

        textpesq_loca.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        textpesq_loca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textpesq_locaKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Search.png"))); // NOI18N
        jLabel7.setText("jLabel4");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textpesq_loca, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(listagemdevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textpesq_loca, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listagemdevolucao)
                    .addComponent(jButton1))
                .addGap(65, 65, 65)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        tabauto.addTab("Aluguer", jPanel3);

        jPanel5.setInheritsPopupMenu(true);
        jPanel5.setOpaque(false);

        funcionario_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13"
            }
        ));
        jScrollPane1.setViewportView(funcionario_table);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("Nome:");

        pesquisa_nome.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        pesquisa_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisa_nomeActionPerformed(evt);
            }
        });
        pesquisa_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pesquisa_nomeKeyReleased(evt);
            }
        });

        btlistar_func.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btlistar_func.setText("Listar todos os funcionarios");
        btlistar_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlistar_funcActionPerformed(evt);
            }
        });

        btnexc_fun.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnexc_fun.setText("Excluir ");
        btnexc_fun.setEnabled(false);
        btnexc_fun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexc_funActionPerformed(evt);
            }
        });

        btn_func_alterar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btn_func_alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Alterar.png"))); // NOI18N
        btn_func_alterar.setText("Editar");
        btn_func_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_func_alterarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Search.png"))); // NOI18N
        jLabel6.setText("jLabel4");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 934, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pesquisa_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btnexc_fun)))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_func_alterar)
                    .addComponent(btlistar_func))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisa_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btlistar_func, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_func_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnexc_fun, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tabauto.addTab("Funcionario", jPanel5);

        table_venda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table_venda);

        txtpesq_venda.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtpesq_venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesq_vendaActionPerformed(evt);
            }
        });
        txtpesq_venda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpesq_vendaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesq_vendaKeyReleased(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton3.setText("Listar todas as Vendas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Search.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Pesquisar Veiculos Vendidos:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpesq_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpesq_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabauto.addTab("Vendas", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(tabauto)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabauto)
                .addContainerGap())
        );

        tabauto.getAccessibleContext().setAccessibleName("Automovel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisa_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisa_nomeActionPerformed

    }//GEN-LAST:event_pesquisa_nomeActionPerformed

    private void btlistar_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlistar_funcActionPerformed
        // TODO add your handling code here:
        String sql = "select id_funcionario as ID, nome, sexo, data_nascimento, cargo, contacto,distrito,morada, tipo_documento,numero_documento,nacionalidade  from funcionario";
        dao x = new dao();

        x.Lista_SqlTabela(sql, funcionario_table);
    }//GEN-LAST:event_btlistar_funcActionPerformed

    private void btnexc_funActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexc_funActionPerformed

        int selecenado = this.funcionario_table.getSelectedRow();
        String id_funcionario = this.funcionario_table.getValueAt(selecenado, 0).toString();
        String nome = this.funcionario_table.getValueAt(selecenado, 1).toString();

        int c = JOptionPane.showConfirmDialog(this, "Deseja deletar  o funcionario?" + nome);
        if (c == 0) {
            String excluir = "DELETE FROM `funcionario` WHERE id_funcionario='" + id_funcionario + "'";
            funcinserir.Excluir(excluir);
            String sql = "select id_funcionario as ID, nome, sexo, data_nascimento, cargo,  contacto  from funcionario";
            dao x = new dao();

            x.Lista_SqlTabela(sql, funcionario_table);

        }
    }//GEN-LAST:event_btnexc_funActionPerformed

    private void pesquisa_nomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisa_nomeKeyReleased
        // TODO add your handling code here:
        String nome_a_pesquisar = pesquisa_nome.getText();
        try {
            String sql = "select id_funcionario as ID, nome, sexo, data_nascimento, cargo, contacto from funcionario where nome like '%" + nome_a_pesquisar + "%' ";
            dao x = new dao();

            x.Lista_SqlTabela(sql, funcionario_table);
        } catch (Exception e) {
            System.out.println("Erro de pesquisa");
        }

    }//GEN-LAST:event_pesquisa_nomeKeyReleased

    private void pesquisar_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisar_nomeActionPerformed

    }//GEN-LAST:event_pesquisar_nomeActionPerformed

    private void pesquisar_nomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisar_nomeKeyReleased
        // TODO add your handling code here:
        String nome_a_pesquisar = pesquisar_nome.getText();
        try {
            String sql = "select id_cliente as ID, nome, sexo, contacto,tipo_documento, numero_documento, nacionalidade, distrito,morada  from cliente where nome like '%" + nome_a_pesquisar + "%' ";
            dao x = new dao();

            x.Lista_SqlTabela(sql, table_cliente);
        } catch (Exception e) {
            System.out.println("Erro de pesquisa");
        }
    }//GEN-LAST:event_pesquisar_nomeKeyReleased

    private void Excluir_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Excluir_clienteActionPerformed
//        int selecenado = this.table_cliente.getSelectedRow();
//        String id_cliente = this.table_cliente.getValueAt(selecenado, 0).toString();
//        String nome = this.table_cliente.getValueAt(selecenado, 1).toString();
//
//        int w = JOptionPane.showConfirmDialog(this, "Deseja deletar  o cliente?" + nome);
//        if (w == 0) {
//            String excluir = "DELETE FROM `cliente` WHERE id_cliente='" + id_cliente + "'";
//            clienteinserir.Excluir(excluir);
//            String sql = "select id_cliente as ID, nome, sexo, contacto,tipo_documento, numero_documento, nacionalidade, distrito,morada  from cliente";
//            dao x = new dao();
//
//            x.Lista_SqlTabela(sql, table_cliente);
//
//        }
    }//GEN-LAST:event_Excluir_clienteActionPerformed

    private void btlistar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlistar_clienteActionPerformed
        String sql = "select id_cliente as ID, nome, sexo, contacto,tipo_documento, numero_documento, nacionalidade, distrito,morada  from cliente";
        dao x = new dao();

        x.Lista_SqlTabela(sql, table_cliente);

    }//GEN-LAST:event_btlistar_clienteActionPerformed

    private void btn_func_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_func_alterarActionPerformed
        int selecenado = this.funcionario_table.getSelectedRow();
         if(selecenado<0){
           JOptionPane.showMessageDialog(null, "Selecione um funcionario");
        }else{
        int id = Integer.parseInt(funcionario_table.getValueAt(funcionario_table.getSelectedRow(), 0) + "");
        String nome = this.funcionario_table.getValueAt(selecenado, 1).toString();
        String sexo = this.funcionario_table.getValueAt(selecenado, 2).toString();
        String data = this.funcionario_table.getValueAt(selecenado, 3).toString();
        String cargo = this.funcionario_table.getValueAt(selecenado, 4).toString();
        int contacto = Integer.parseInt(this.funcionario_table.getValueAt(selecenado, 5) + "");
        String distrito = this.funcionario_table.getValueAt(selecenado, 6).toString();
        String morada = this.funcionario_table.getValueAt(selecenado, 7).toString();
        String numero_documento = this.funcionario_table.getValueAt(selecenado, 9).toString();
        String tipo_documento = this.funcionario_table.getValueAt(selecenado, 8).toString();
        String naciolidade = this.funcionario_table.getValueAt(selecenado, 10).toString();
        func.setId_funcionario(id);
        func.setNome(nome);
        func.setSexo(sexo);
        func.setData_nascimento(data);
        func.setCargo(cargo);
        func.setContacto(contacto);
        func.setDistrito(distrito);
        func.setMorada(morada);
        func.setNumero_documento(numero_documento);
        func.setContacto(contacto);
        func.setTipo_documento(tipo_documento);
        func.setNacionalidade(naciolidade);

        this.setVisible(false);
        Cadastrafunc cadastrar = new Cadastrafunc();
        cadastrar.Pintar();

        JFMenu.jDesktopPane1.add(cadastrar);
        cadastrar.show();
        cadastrar.setVisible(true);
         }

    }//GEN-LAST:event_btn_func_alterarActionPerformed

    private void btn_altera_clieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_altera_clieActionPerformed
        // TODO add your handling code here:
        int selecenado = this.table_cliente.getSelectedRow();
        if(selecenado<0){
           JOptionPane.showMessageDialog(null, "Selecione um cliente");
        }else{
        int id = Integer.parseInt(table_cliente.getValueAt(table_cliente.getSelectedRow(), 0) + "");
        String nome = this.table_cliente.getValueAt(selecenado, 1).toString();
        String sexo = this.table_cliente.getValueAt(selecenado, 2).toString();
        int contacto = Integer.parseInt(this.table_cliente.getValueAt(selecenado, 3).toString());
        String tipo_documento = this.table_cliente.getValueAt(selecenado, 4).toString();
        String numero_documento = this.table_cliente.getValueAt(selecenado, 5).toString();
        String nacionalidade = this.table_cliente.getValueAt(selecenado, 6).toString();
        String distrito = this.table_cliente.getValueAt(selecenado, 7).toString();
        String morada = this.table_cliente.getValueAt(selecenado, 8).toString();
        cliente.setId_cliente(id);
        cliente.setTipo_documento(tipo_documento);
        cliente.setNacionalidade(nacionalidade);
        cliente.setNome(nome);
        cliente.setSexo(sexo);
        cliente.setContacto(contacto);
        cliente.setDistrito(distrito);
        cliente.setMorada(morada);
        cliente.setNumero_documento(numero_documento);
        this.setVisible(false);
        cadastrocliente cadastrar = new cadastrocliente();
        JFMenu.jDesktopPane1.add(cadastrar);
        cadastrar.Pintar();
        cadastrar.show();
        }
    }//GEN-LAST:event_btn_altera_clieActionPerformed

    private void listar_automoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listar_automoveisActionPerformed
        // TODO add your handling code here:
        String sql = "select id_automovel as ID,modelo,marca,matricula,fornecedor,combustivel,numero_de_assento,ano,cor, preco,estado,categoria_servico from automovel";
        dao x = new dao();
        x.Lista_SqlTabela(sql, table_automovel);
    }//GEN-LAST:event_listar_automoveisActionPerformed


    private void alterar_automovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterar_automovelActionPerformed
        // TODO add your handling code here:
        
        int seleceonado = this.table_automovel.getSelectedRow();
        if(seleceonado<0){
           JOptionPane.showMessageDialog(null, "Selecione um automovel");
        }else{
            
       
        int id = Integer.parseInt(this.table_automovel.getValueAt(table_automovel.getSelectedRow(), 0) + "");
        String modelo = this.table_automovel.getValueAt(seleceonado, 1).toString();
        String marca = this.table_automovel.getValueAt(seleceonado, 2).toString();
        String cor = this.table_automovel.getValueAt(seleceonado, 8).toString();
        String numero_assento = this.table_automovel.getValueAt(seleceonado, 6).toString();
        String matricula = this.table_automovel.getValueAt(seleceonado, 3).toString();
        String fornecedor = this.table_automovel.getValueAt(seleceonado, 4).toString();
        String combustivel = this.table_automovel.getValueAt(seleceonado, 5).toString();
        String ano = this.table_automovel.getValueAt(seleceonado, 7).toString();
        Float preco = Float.parseFloat(this.table_automovel.getValueAt(seleceonado, 9) + "");
        boolean g = Boolean.parseBoolean(this.table_automovel.getValueAt(seleceonado, 10).toString());
        String categoria = this.table_automovel.getValueAt(seleceonado, 11).toString();

        veiculo.setId_Automovel(id);
        veiculo.setModelo(modelo);
        veiculo.setMarca(marca);
        veiculo.setMatricula(matricula);
        veiculo.setAno(ano);
        veiculo.setEstado(g);

        veiculo.setCombustivel(combustivel);
        veiculo.setCor(cor);
        veiculo.setFornecedor(fornecedor);
        veiculo.setNumero_de_assento(numero_assento);
        veiculo.setPreco(preco);
        veiculo.setCategoria_servico(categoria);

        this.setVisible(false);

        cadastraautomovel cadastra = new cadastraautomovel();
        cadastra.Pintar();

        JFMenu.jDesktopPane1.add(cadastra);
        cadastra.show();
        cadastra.setVisible(true);
 }
    }//GEN-LAST:event_alterar_automovelActionPerformed

    private void btnexcluir_veiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluir_veiculoActionPerformed
        // TODO add your handling code here:
        int selecenado = this.table_automovel.getSelectedRow();
        String id_automovel = this.table_automovel.getValueAt(selecenado, 0).toString();
        String marca = this.table_automovel.getValueAt(selecenado, 2).toString();

        int v = JOptionPane.showConfirmDialog(this, "Deseja deletar  o Automovel?" + marca);
        if (v == 0) {
            String excluir = "DELETE FROM `automovel` WHERE id_automovel='" + id_automovel + "'";
            automovelinserir.Excluir(excluir);
            String sql = "select id_automovel as ID,modelo,marca,matricula,fornecedor,combustivel,numero_de_assento,ano,cor, preco,estado, categoria_servico from automovel";
            dao x = new dao();

            x.Lista_SqlTabela(sql, table_automovel);
        }
    }//GEN-LAST:event_btnexcluir_veiculoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT aluger.id_aluger,data_inicio,data_termino, hora_termino,cliente.nome,cliente.contacto, automovel.marca,automovel.modelo,veiculo FROM aluger,cliente,automovel where aluger.id_cliente=cliente.id_cliente and aluger.id_automovel= automovel.id_automovel AND `veiculo` LIKE 'Alugado' ORDER BY `id_aluger` ASC";
        dao x = new dao();

        x.Lista_SqlTabela(sql, table_aluguer);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void listagemdevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listagemdevolucaoActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT aluger.id_aluger,data_inicio,data_termino, hora_termino,cliente.nome,cliente.contacto, automovel.marca,automovel.modelo,veiculo FROM aluger,cliente,automovel where aluger.id_cliente=cliente.id_cliente and aluger.id_automovel= automovel.id_automovel AND `veiculo` LIKE 'Devolvido' ORDER BY `id_aluger` ASC";
        dao x = new dao();
        x.Lista_SqlTabela(sql, table_aluguer);
    }//GEN-LAST:event_listagemdevolucaoActionPerformed

    private void textpesq_locaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textpesq_locaKeyReleased
        
        
        String sql= "SELECT aluger.id_aluger,data_inicio,data_termino, hora_termino,cliente.nome,cliente.contacto, automovel.marca,automovel.modelo,veiculo FROM aluger,cliente,automovel where aluger.id_cliente=cliente.id_cliente and aluger.id_automovel= automovel.id_automovel AND `veiculo` LIKE 'Alugado'AND automovel.marca LIKE '%"+textpesq_loca.getText()+"%' ORDER BY `id_aluger` ASC";
        dao x = new dao();

        x.Lista_SqlTabela(sql, table_aluguer);
    }//GEN-LAST:event_textpesq_locaKeyReleased

    private void txtpesq_vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesq_vendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesq_vendaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT venda.id_venda, cliente.nome, cliente.contacto, automovel.marca, automovel.modelo,automovel.cor,automovel.matricula, venda.tipo_pagamento,venda.descontos, venda.valor_venda FROM venda,cliente,automovel where venda.id_cliente=cliente.id_cliente and venda.id_automovel= automovel.id_automovel ";
            dao x = new dao();

            x.Lista_SqlTabela(sql, table_venda);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtpesq_vendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesq_vendaKeyPressed
//        // TODO add your handling code here:
//        
//        String sql = "SELECT venda.id_venda, cliente.nome, cliente.contacto, automovel.marca, automovel.modelo,automovel.cor,automovel.matricula, venda.tipo_pagamento,venda.descontos, venda.valor_venda FROM venda,cliente,automovel where venda.id_cliente=cliente.id_cliente and venda.id_automovel= automovel.id_automovel AND marca LIKE '%"+txtpesq_venda.getText()+"%' ";
//            dao x = new dao();
//
//            x.Lista_SqlTabela(sql, table_venda);
    }//GEN-LAST:event_txtpesq_vendaKeyPressed

    private void txtmarcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmarcaKeyReleased
        // TODO add your handling code here:\1
        String sql = "select id_automovel as ID,modelo,marca,matricula,fornecedor,combustivel,numero_de_assento,ano,cor, preco,categoria_servico,estado from automovel where marca Like'%"+txtmarca.getText()+"%' ";
        dao x = new dao();

        x.Lista_SqlTabela(sql, table_automovel);
        
    }//GEN-LAST:event_txtmarcaKeyReleased

    private void txtpesq_vendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesq_vendaKeyReleased
        // TODO add your handling code here:
        String sql = "SELECT venda.id_venda, cliente.nome, cliente.contacto, automovel.marca, automovel.modelo,automovel.cor,automovel.matricula, venda.tipo_pagamento,venda.descontos, venda.valor_venda FROM venda,cliente,automovel where venda.id_cliente=cliente.id_cliente and venda.id_automovel= automovel.id_automovel And automovel.marca Like'%"+txtpesq_venda.getText()+"%' ";
        dao x = new dao();

        x.Lista_SqlTabela(sql, table_venda);
    }//GEN-LAST:event_txtpesq_vendaKeyReleased
         
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Excluir_cliente;
    private javax.swing.JButton alterar_automovel;
    public javax.swing.JButton btlistar_cliente;
    private javax.swing.JButton btn_altera_clie;
    private javax.swing.JButton btn_func_alterar;
    private javax.swing.JButton btnexc_fun;
    private javax.swing.JButton btnexcluir_veiculo;
    private javax.swing.JTable funcionario_table;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton listagemdevolucao;
    private javax.swing.JButton listar_automoveis;
    private javax.swing.JTextField pesquisa_nome;
    private javax.swing.JTextField pesquisar_nome;
    public javax.swing.JTabbedPane tabauto;
    private javax.swing.JTable table_aluguer;
    private javax.swing.JTable table_automovel;
    private javax.swing.JTable table_cliente;
    private javax.swing.JTable table_venda;
    private javax.swing.JTextField textpesq_loca;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtpesq_venda;
    // End of variables declaration//GEN-END:variables

}
