/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Classes.conexao;
import Classes.usuario;
import static Formularios.freLogin.func;
import static Formularios.freLogin.user;
import Interfaces.usuarioOperacao;
import java.sql.PreparedStatement;
import java.sql.Connection;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author kedson dos Anjos
 */
public class TelaUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaUsuario
     */
    public TelaUsuario() {
        initComponents();
        listar();
    }

    public void preencher() {
         this.txtusu.setText(user.getNome());
        this.txtsenha.setText(user.getSenha());
        this.btnSalvar.setEnabled(false);
        this.boxusuariu.setEnabled(false);
    }
    public void desativarBTA(){
        this.btnalterar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        txtusu = new javax.swing.JTextField();
        txtconfisenha = new javax.swing.JPasswordField();
        javax.swing.JButton cancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        boxusuariu = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnalterar = new javax.swing.JButton();
        txtsenha = new javax.swing.JPasswordField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("Nome Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 50, -1, 33));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("Senha:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 115, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Confirmar Senha:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 149, -1, -1));

        txtusu.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        getContentPane().add(txtusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 50, 177, 33));

        txtconfisenha.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        txtconfisenha.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtconfisenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconfisenhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtconfisenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 177, 30));

        cancelar.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        cancelar.setForeground(new java.awt.Color(255, 0, 0));
        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/btncancel1.png"))); // NOI18N
        cancelar.setText("Cancelar");
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        btnSalvar.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(0, 0, 255));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/btnsave.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        boxusuariu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxusuariuItemStateChanged(evt);
            }
        });
        boxusuariu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxusuariuActionPerformed(evt);
            }
        });
        getContentPane().add(boxusuariu, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 11, 177, 28));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Funcionario:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 15, -1, 24));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/user.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 19, 120, 127));

        btnalterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Alterar.png"))); // NOI18N
        btnalterar.setText("Alterar");
        btnalterar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnalterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        txtsenha.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        txtsenha.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsenhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 109, 177, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        usuario usu = new usuario();
        usuarioOperacao insert = new usuarioOperacao();
        usu.setNome(this.txtusu.getText());
        usu.setSenha(this.txtsenha.getText());
        usu.setConfirmarsenha(this.txtconfisenha.getText());
        boolean ver = insert.ConfSenha(this.txtsenha.getText(), this.txtconfisenha.getText());
        if (ver == true) {
            usu.setId_funcionario(func.getId_funcionario());
            insert.Cadastra(usu);
            cancelar();
        } else {
            JOptionPane.showMessageDialog(null, "Senha ou Confirma senha está imcopativel");
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtconfisenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconfisenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconfisenhaActionPerformed

    private void boxusuariuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxusuariuItemStateChanged
        // TODO add your handling code here:
        listarPesquisa();
    }//GEN-LAST:event_boxusuariuItemStateChanged

    private void btnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarActionPerformed
        // TODO add your handling code here:
        usuario al = new usuario();
        usuarioOperacao insert = new usuarioOperacao();
        if (this.txtusu.getText().length()<=0||this.txtsenha.getText().length()<=0||this.txtconfisenha.getText().length()<=0) {
            JOptionPane.showMessageDialog(null,"Esta acção nessecita de todos os campos preenchidos" );
        } else {
        
        al.setNome(this.txtusu.getText());
        al.setSenha(this.txtsenha.getText());
        al.setConfirmarsenha(this.txtconfisenha.getText());
        boolean ver = insert.ConfSenha(this.txtsenha.getText(), this.txtconfisenha.getText());
        if (ver == true) {
            al.setId_user(user.getId_user());
            System.out.println(user.getId_user());
            insert.Alterar(al);
            cancelar();
        } else {
            JOptionPane.showMessageDialog(null, "Senha ou Confirma senha está imcopativel");
        }

        }
        
    }//GEN-LAST:event_btnalterarActionPerformed

    private void txtsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsenhaActionPerformed

    private void boxusuariuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxusuariuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxusuariuActionPerformed
    public void listar() {
        conexao con = new conexao();
        Connection co = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        co = con.getConnection();
        DefaultComboBoxModel defaultComboboxModel = new DefaultComboBoxModel();
        boxusuariu.setModel(defaultComboboxModel);
        String sql = "SELECT nome FROM `funcionario` WHERE `cargo` LIKE 'Recepcionista'";
        try {
            ps = co.prepareStatement(sql);
            rs = ps.executeQuery();
            System.out.println("Ok executandos" + sql);
            rs = ps.executeQuery();
            defaultComboboxModel.removeAllElements();
            int v = 0;
            while (rs.next() & v < 4) {

                defaultComboboxModel.addElement(rs.getString("nome"));

                v++;

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        con.closeConnection();

    }

    public void listarPesquisa() {
        conexao con = new conexao();
        Connection co = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        co = con.getConnection();
        int linha = boxusuariu.getSelectedIndex();

        if (linha >= 0) {
            try {
                String sql = "SELECT *  FROM `funcionario` WHERE `nome` LIKE '%" + boxusuariu.getSelectedItem() + "%' ";
                ps = co.prepareStatement(sql);
                rs = ps.executeQuery();
                rs.first();
                func.setId_funcionario((rs.getInt("id_funcionario")));

            } catch (SQLException ex) {
                System.out.println(ex);
            }
        } else {
        }
        con.closeConnection();
    }

    public void cancelar() {
        this.txtusu.setText("");
        this.txtconfisenha.setText("");
        this.txtsenha.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JComboBox<String> boxusuariu;
    javax.swing.JButton btnSalvar;
    javax.swing.JButton btnalterar;
    javax.swing.JLabel jLabel5;
    javax.swing.JPasswordField txtconfisenha;
    javax.swing.JPasswordField txtsenha;
    javax.swing.JTextField txtusu;
    // End of variables declaration//GEN-END:variables
}
